zolex_grpc:
    server:
        options:
            debug: true
    clients:
        Modix\Grpc\Service\Example\v1\QueryClient:
            host: host.docker.internal
            port: 3886
        default:
            host: host.docker.internal
            port: 3886
