#rpc:
#  enable: true
#  listen: tcp://127.0.0.1:6001

metric:
  enable: false

# grpc service configuration.
grpc:
  listen: tcp://0.0.0.0:3886
  proto: "proto/services.proto"
  workers.command: "php bin/worker.php"
  #tls.key:  "config/tls/app.key"
  #tls.cert: "config/tls/app.crt"
  workers:
    pool:
      numWorkers: 1
      maxJobs: 1

# control the max memory usage
limit:
  services:
    grpc.maxMemory: 100

debugger:
  HistorySize: 2000
  address: :8089
