version: '2'

services:
  protoc:
    #build:
    #  dockerfile: docker/protoc/Dockerfile
    #  context: .
    image: zolex/protoc-grpc:0.0.1
    working_dir: /var/www
    volumes:
      - .:/var/www
      - ./rr/plugins/debugger:/usr/lib/go/src/plugins/debugger

  server:
    build:
      dockerfile: docker/server/Dockerfile-ext
      context: .
    #image: zolex/grpc-php-server:0.0.1
    working_dir: /var/www
    volumes:
      - .:/var/www
    ports:
      - 3886:3886
    networks:
      - app_network

  client:
    build:
      dockerfile: docker/client/Dockerfile-ext
      context: .
    #image: zolex/grpc-php-client:0.0.1
    command: -exec "while true; do sleep 1000; done"
    working_dir: /var/www
    volumes:
      - .:/var/www

  db:
    image: mysql:latest
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - "3333:3306"
    volumes:
      - ./var/mysql_data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: grpc
      MYSQL_DATABASE: grpc
      MYSQL_USER: grpc
      MYSQL_PASSWORD: grpc
    networks:
      - app_network
  envoy:
    build:
      dockerfile: docker/envoy/Dockerfile
      context: .
    container_name: EnvoyToPHPServer
    ports:
      - '9901:9901'
      - '8080:8080'
    networks:
      - app_network
  grpcui:
    build:
      dockerfile: docker/grpcui/Dockerfile
      context: .
    command: /root/go/bin/grpcui -plaintext -import-path /var/proto/ -proto services.proto -bind 0.0.0.0 -port 1337 server:3886
    ports:
      - '1337:1337'
    volumes:
      - ./proto:/var/proto
    depends_on:
      - server
    networks:
      - app_network
networks:
  app_network:
    driver: bridge