version: '2'

services:
  protoc:
    #build:
    #  dockerfile: docker/protoc/Dockerfile
    #  context: .
    image: zolex/protoc-php-server:0.0.2
    working_dir: /var/www
    volumes:
      - .:/var/www

  server:
    #build:
    #  dockerfile: docker/server/Dockerfile
    #  context: .
    image: zolex/grpc-php-server:0.0.1
    working_dir: /var/www
    volumes:
      - .:/var/www
    ports:
      - 3886:3886

  client:
    #build:
    #  dockerfile: docker/client/Dockerfile
    #  context: .
    image: zolex/grpc-php-client:0.0.1
    command: -exec "while true; do sleep 1000; done"
    working_dir: /var/www
    volumes:
      - .:/var/www