monolog:
    handlers:
        main:
            type: stream
            path: "%kernel.logs_dir%/%kernel.environment%.log"
            level: debug
            channels: ["!event"]
        console:
            type: service
            id: App\Logger\GoridgeRpcHandler
            channels: ["!event"]
