monolog:
    handlers:
        main:
            type: stream
            path: "%kernel.logs_dir%/%kernel.environment%.log"
            level: debug
            channels: ["!event"]
        console:
            type: service
            id: zolex.grpc.logger.handler
            channels: ["!event"]

        # requires the GoridgeRpcHandler to be configured as a service
        #rpc:
        #    type: service
        #    id: Zolex\GrpcBundle\Logger\GoridgeRpcHandler
        #    channels: ["!event"]
