parameters:
    grpc_options:
        debug: '%kernel.debug%'

services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\:
        resource: '../src/*'
        exclude: '../src/{DependencyInjection,Entity,Migrations,Test,Kernel.php}'

    # remember to add sockets and json php extensions when enabling this...
    #Spiral\Goridge\SocketRelay:
    #    arguments: ['127.0.0.1', 6001]
    #Spiral\Goridge\RPC:
    #    arguments: ['@Spiral\Goridge\SocketRelay']

    Spiral\RoadRunner\Worker:
        arguments: ['@App\Goridge\RelayWrapper']
    Spiral\GRPC\Server:
        public: true
        arguments:
            $options: '%grpc_options%'
        calls:
          - registerService: ['Modix\Grpc\Example\ExampleInterface', '@App\Service\ExampleService']
          - registerService: ['Modix\Grpc\Other\OtherInterface', '@App\Service\OtherService']
          - serve: ['@Spiral\RoadRunner\Worker']

    App\Doctrine\EntityManager:
        class: App\Doctrine\EntityManager
        decorates: doctrine.orm.default_entity_manager
        arguments: [ '@App\Doctrine\EntityManager.inner' ]