parameters:
    grpc_options:
        debug: '%kernel.debug%'
    grpc_clients:
        # options by classname
        Modix\Grpc\Service\Example\v1\QueryClient:
            host: host.docker.internal
            port: 3886
        # for all unspecified clients
        default:
            host: host.docker.internal
            port: 3886

services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\:
        resource: '../src/*'
        exclude: '../src/{DependencyInjection,Entity,Migrations,Test,Kernel.php}'

    # remember to add sockets and json php extensions when enabling this...
    #Spiral\Goridge\SocketRelay:
    #    arguments: ['127.0.0.1', 6001]
    #Spiral\Goridge\RPC:
    #    arguments: ['@Spiral\Goridge\SocketRelay']
    #Zolex\GrpcBundle\Logger\GoridgeRpcHandler: ~
