parameters:
    grpc_options:
        debug: '%kernel.debug%'

services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\:
        resource: '../src/*'
        exclude: '../src/{DependencyInjection,Entity,Migrations,Test,Kernel.php}'

    Spiral\RoadRunner\Worker:
        arguments: ['@App\Goridge\RelayWrapper']
    Spiral\GRPC\Server:
        public: true
        arguments:
            $options: '%grpc_options%'
        calls:
          - registerService: ['Modix\Grpc\Example\ExampleInterface', '@App\Service\ExampleService']
          - registerService: ['Modix\Grpc\Other\OtherInterface', '@App\Service\OtherService']
          - serve: ['@Spiral\RoadRunner\Worker']


