services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\:
        resource: '../src/*'
        exclude: '../src/{DependencyInjection,Entity,Migrations,Test,Kernel.php}'

    Modix\Grpc\Service\:
        resource: '../grpc-php/Modix/Grpc/Service/**/*Client.php'


    # remember to add sockets and json php extensions when enabling this...
    #Spiral\Goridge\SocketRelay:
    #    arguments: ['127.0.0.1', 6001]
    #Spiral\Goridge\RPC:
    #    arguments: ['@Spiral\Goridge\SocketRelay']
    #Zolex\GrpcBundle\Logger\GoridgeRpcHandler: ~
